---

# https://www.redhat.com/en/blog/introducing-microsoft-active-directory-inventory-plug-ansible
# https://thecloudmarathoner.com/index.php/2021/10/28/how-to-create-a-free-azure-active-directory-developer-tenant-%F0%9F%A4%94/
# https://github.com/joshinryz/ansible_ldap_inventory/tree/master
- name: Get dynamic RHEL nodes and assign them to groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: debug
      debug:
        msg: '{{ lookup("ansible.builtin.env", "MICROSOFT_AD_LDAP_SERVER") }}'

    # - name: Get the SID for all user accounts as a LDAP filter
    #   microsoft.ad.object_info:
    #     ldap_filter: (&(objectClass=user)(objectCategory=Person))
    #     properties:
    #     - objectSid

    # - name: Ensure user bob is present with address information
    #   microsoft.ad.user:
    #     domain_server: ldaps://6y2twd.onmicrosoft.com:636
    #     domain_username: cparada@6y2twd.onmicrosoft.com
    #     domain_password: "{{ password }}"
    #     identity: bob
    #     firstname: Bob
    #     surname: Smith
    #     company: BobCo
    #     password: B0bP4ssw0rd
    #     state: present
    #     groups:
    #       set:
    #       - Domain Admins
    #     street: 123 4th St.
    #     city: Sometown
    #     state_province: IN
    #     postal_code: 12345
    #     country: US
    #     attributes:
    #       set:
    #         telephoneNumber: 555-123456