---

- name: Get dynamic RHEL nodes and assign them to groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

    - name: Get the SID for all user accounts as a LDAP filter
      microsoft.ad.object_info:
        ldap_filter: (&(objectClass=user)(objectCategory=Person))
        properties:
        - objectSid

    - name: Ensure user bob is present with address information
      microsoft.ad.user:
        identity: bob
        firstname: Bob
        surname: Smith
        company: BobCo
        password: B0bP4ssw0rd
        state: present
        groups:
          set:
          - Domain Admins
        street: 123 4th St.
        city: Sometown
        state_province: IN
        postal_code: 12345
        country: US
        attributes:
          set:
            telephoneNumber: 555-123456